=== vickymx/Multilingua/functionaltexts.dtd
<!ELEMENT texts (entry+)>

<!ELEMENT entry (category, lang+)>
<!ATTLIST entry
  key CDATA #REQUIRED
  published (yes|no) "yes"
>

<!ELEMENT category (#PCDATA)>

<!ELEMENT lang (title, content)>
<!ATTLIST lang code (bg|en|fr) #REQUIRED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT content (#PCDATA | p | sentence)*>

<!ELEMENT p (#PCDATA)>

<!ELEMENT sentence (word+)>
<!ATTLIST sentence id ID #IMPLIED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word
  lemma CDATA #IMPLIED
  upos  (ADJ|ADP|ADV|AUX|CCONJ|DET|INTJ|NOUN|NUM|PART|PRON|PROPN|PUNCT|SCONJ|SYM|VERB|X) #REQUIRED
  feats CDATA #IMPLIED
  misc  CDATA #IMPLIED

>

=== vickymx/Multilingua/functionaltexts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texts SYSTEM "functionaltexts.dtd">
<texts>

<!-- ========== MEDICINE (10) ========== -->

<entry key="abidoax" published="yes">
    <category>medicine</category>
    <lang code="bg">
    <title>Абидоакс</title>
    <content>
        <p>Абидоакс съдържа активното вещество дабигатран етексилат и принадлежи към група лекарства, наречени антикоагуланти. Той блокира действието на вещество в организма, което участва в образуването на кръвни съсиреци.</p>
        <p>Възрастни: предотвратяване на венозни тромби след протезиране на колянна или тазобедрена става. Деца: разтваря съществуващи тромби и предотвратява повторно образуване.</p>
        <sentence id="bg_abidoax_s1">
        <word upos="PROPN" lemma="Абидоакс">Абидоакс</word>
        <word upos="VERB" lemma="съдържа" feats="Mood=Ind|Tense=Pres|Person=3|Number=Sing">съдържа</word>
        <word upos="ADJ" lemma="активен" feats="Degree=Pos|Definite=Def">активното</word>
        <word upos="NOUN" lemma="вещество" feats="Number=Sing|Definite=Def">вещество</word>
        <word upos="PROPN" lemma="дабигатран">дабигатран</word>
        <word upos="PROPN" lemma="етексилат">етексилат</word>
        <word upos="CCONJ">и</word>
        <word upos="VERB" lemma="принадлежа" feats="Mood=Ind|Tense=Pres|Person=3|Number=Sing">принадлежи</word>
        <word upos="ADP">към</word>
        <word upos="NOUN" lemma="група" feats="Number=Sing">група</word>
        <word upos="NOUN" lemma="лекарство" feats="Number=Plur">лекарства</word>
        <word upos="NOUN" lemma="антикоагулант" feats="Number=Plur">антикоагуланти</word>
        <word upos="PUNCT">.</word>
        </sentence>
    </content>
    </lang>
    <lang code="en">
    <title>Abidoax</title>
    <content>
        <p>Abidoax contains the active substance dabigatran etexilate and belongs to a group of medicines called anticoagulants. It blocks a substance involved in the formation of blood clots.</p>
        <p>Adults: prevention of venous clots after knee or hip replacement. Children: dissolves existing clots and prevents recurrence.</p>
    </content>
    </lang>
    <lang code="fr">
    <title>Abidoax</title>
    <content>
        <p>Abidoax contient le principe actif dabigatran étexilate et appartient à un groupe de médicaments appelés anticoagulants. Il bloque une substance impliquée dans la formation de caillots sanguins.</p>
        <p>Adultes : prévention des caillots veineux après prothèse du genou/de la hanche. Enfants : dissout les caillots existants et empêche leur récidive.</p>
    </content>
    </lang>
</entry>

<entry key="ibuprofen-accord" published="yes">
    <category>medicine</category>
    <lang code="bg">
    <title>Ибупрофен Акорд</title>
    <content>
        <p>Ибупрофен Акорд е НСПВС (нестероидно противовъзпалително средство) за краткосрочно лечение на висока температура и лека до умерена болка, включително дисменорея.</p>
        <p>Дългосрочно симптоматично лечение на болка и възпаление при хронични възпалителни ревматични заболявания. Подходящ за възрастни и деца &gt; 6 години (20 kg).</p>
        <sentence id="bg_ibu_s1">
        <word upos="PROPN" lemma="Ибупрофен">Ибупрофен</word>
        <word upos="PROPN" lemma="Акорд">Акорд</word>
        <word upos="AUX" lemma="съм" feats="Mood=Ind|Tense=Pres|Person=3|Number=Sing">е</word>
        <word upos="NOUN" lemma="НСПВС">НСПВС</word>
        <word upos="PUNCT">(</word>
        <word upos="ADJ" lemma="нестероидно">нестероидно</word>
        <word upos="ADJ" lemma="противовъзпалително">противовъзпалително</word>
        <word upos="NOUN" lemma="средство" feats="Number=Sing">средство</word>
          <word upos="PUNCT">)</word>
          <word upos="ADP">за</word>
          <word upos="NOUN" lemma="лечение" feats="Number=Sing">лечение</word>
          <word upos="PUNCT">.</word>
        </sentence>
      </content>
    </lang>
    <lang code="en">
      <title>Ibuprofen Accord</title>
      <content>
        <p>NSAID for short-term treatment of high fever and mild-to-moderate pain, including dysmenorrhea.</p>
        <p>Long-term symptomatic treatment of pain/inflammation in chronic inflammatory rheumatic diseases; adults and children &gt; 6 years (20 kg).</p>
      </content>
    </lang>
    <lang code="fr">
      <title>Ibuprofène Accord</title>
      <content>
        <p>AINS pour le traitement à court terme de la fièvre élevée et des douleurs légères à modérées, y compris la dysménorrhée.</p>
        <p>Traitement symptomatique au long cours de la douleur et de l’inflammation dans les maladies rhumatismales inflammatoires chroniques; adultes et enfants &gt; 6 ans (20 kg).</p>
      </content>
    </lang>
  </entry>

  <entry key="paracetamol" published="yes">
    <category>medicine</category>
    <lang code="bg">
      <title>Парацетамол</title>
      <content>
        <p>Парацетамолът е аналгетик и антипиретик. Ефективен при лека до умерена остра и хронична болка и за понижаване на температурата при треска.</p>
        <sentence id="bg_para_s1">
          <word upos="NOUN" lemma="парацетамол" feats="Definite=Def|Number=Sing">Парацетамолът</word>
          <word upos="AUX" lemma="съм" feats="Mood=Ind|Tense=Pres|Person=3|Number=Sing">е</word>
          <word upos="NOUN" lemma="аналогетик">аналгетик</word>
          <word upos="CCONJ">и</word>
          <word upos="NOUN" lemma="антипиретик">антипиретик</word>
          <word upos="PUNCT">.</word>
        </sentence>
      </content>
    </lang>
    <lang code="en">
      <title>Paracetamol</title>
      <content>
        <p>Analgesic and antipyretic. Effective for mild to moderate acute and chronic pain; reduces fever.</p>
      </content>
    </lang>
    <lang code="fr">
      <title>Paracétamol</title>
      <content>
        <p>Analgésique et antipyrétique. Efficace contre les douleurs aiguës/chroniques légères à modérées; réduit la fièvre.</p>
      </content>
    </lang>
  </entry>

  <entry key="kaslirol-250mg-5ml-syrup" published="yes">
    <category>medicine</category>
    <lang code="bg">
      <title>Каслирол 250 mg/5 ml сироп</title>
      <content>
        <p>Съдържа карбоцистеин (муколитик). За възрастни и деца &gt; 15 години при респираторни заболявания със затруднено отхрачване; подпомага изчистването на бронхиални секрети.</p>
        <sentence id="bg_kas_s1">
          <word upos="NOUN" lemma="сироп">Сироп</word>
          <word upos="PROPN" lemma="Каслирол">Каслирол</word>
          <word upos="VERB" lemma="съдържа" feats="Mood=Ind|Tense=Pres|Person=3|Number=Sing">съдържа</word>
          <word upos="NOUN" lemma="карбоцистеин">карбоцистеин</word>
          <word upos="PUNCT">(</word>
          <word upos="NOUN" lemma="муколитик">муколитик</word>
          <word upos="PUNCT">)</word>
          <word upos="PUNCT">.</word>
        </sentence>
      </content>
    </lang>
    <lang code="en">
      <title>Kaslirol 250 mg/5 ml syrup</title>
      <content>
        <p>Contains carbocisteine (mucolytic). For adults and &gt; 15 years with respiratory diseases and difficult expectoration; helps clear bronchial secretions.</p>
      </content>
    </lang>
    <lang code="fr">
      <title>Kaslirol 250 mg/5 ml sirop</title>
      <content>
        <p>Contient de la carbocistéine (mucolytique). Indiqué chez l’adulte et &gt; 15 ans; facilite l’expectoration.</p>
      </content>
    </lang>
  </entry>

  <entry key="hexoral-solution" published="yes">
    <category>medicine</category>
    <lang code="bg">
      <title>Хексорал 0,1 g/100 ml разтвор</title>
      <content>
        <p>Антисептик (хексетидин) при леки орофарингеални инфекции, гингивит, възпалено гърло, афти, халитоза; преди/след орофарингеална операция; ежедневна орална хигиена.</p>
        <sentence id="bg_hex_s1">
          <word upos="PROPN" lemma="Хексорал">Хексорал</word>
          <word upos="AUX" lemma="съм" feats="Mood=Ind|Tense=Pres|Person=3|Number=Sing">е</word>
          <word upos="NOUN" lemma="антисептик">антисептик</word>
          <word upos="PUNCT">(</word>
          <word upos="PROPN" lemma="хексетидин">хексетидин</word>
          <word upos="PUNCT">)</word>
          <word upos="PUNCT">.</word>
        </sentence>
      </content>
    </lang>
    <lang code="en">
      <title>Hexoral 0.1 g/100 ml solution</title>
      <content>
        <p>Antiseptic (hexetidine) indicated for minor oropharyngeal infections, gingivitis, sore throat, recurrent aphthous ulcers, halitosis; peri-operative use; daily oral hygiene.</p>
      </content>
    </lang>
    <lang code="fr">
      <title>Hexoral 0,1 g/100 ml solution buccale</title>
      <content>
        <p>Antiseptique à base d’hexétidine; infections oropharyngées mineures, gingivite, maux de gorge, aphtes récidivants, halitose; avant/après chirurgie; hygiène quotidienne.</p>
      </content>
    </lang>
  </entry>

  <entry key="myprofen-100mg" published="yes">
    <category>medicine</category>
    <lang code="bg">
      <title>Мипрофен 100 mg таблетки</title>
      <content>
        <p>Флурбипрофен (НСПВС). Показания: остеоартрит, ревматични заболявания, анкилозиращ спондилит, мускулно-скелетни болки; зъбобол, постоперативна, менструална болка, мигрена.</p>
        <sentence id="bg_myp_s1">
          <word upos="PROPN" lemma="Мипрофен">Мипрофен</word>
          <word upos="NUM">100</word>
          <word upos="SYM">mg</word>
          <word upos="NOUN" lemma="таблетка" feats="Number=Plur">таблетки</word>
          <word upos="AUX" lemma="съм" feats="Mood=Ind|Tense=Pres|Person=3|Number=Plur">са</word>
          <word upos="NOUN" lemma="НСПВС">НСПВС</word>
          <word upos="PUNCT">.</word>
        </sentence>
      </content>
    </lang>
    <lang code="en">
      <title>Myprofen 100 mg tablets</title>
      <content>
